/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Cory' at '11/4/16 11:35 PM' with Gradle 2.13
 *
 * @author Cory, @date 11/4/16 11:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
